[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/bin/sh -c 'prisma migrate deploy --schema=/app/apps/api/prisma/schema.prisma && node /app/apps/api/dist/index.js'"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
