import type { Metadata } from 'next';
import { notFound } from 'next/navigation';

const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://localhost:3001';

type Highlight = { title: string; description: string };
type Section = {
  assessmentId: string;
  repoOwner: string;
  repoName: string;
  overallScore: number;
  headline: string;
  summary: string;
  role: string;
  duration: string;
  techStack: string[];
  highlights: Highlight[];
  impact: string;
};
type Doc = { id: string; name: string; sections: Section[]; createdAt: string };

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const doc = await getPublicDoc(id);
  const title = doc?.name ?? 'Software Portfolio';
  return {
    title,
    openGraph: {
      title,
      description: 'Software portfolio generated by Jobclaw from real GitHub repositories.',
      images: [{ url: `/portfolio/${id}/opengraph-image`, width: 1200, height: 630 }],
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description: 'Software portfolio generated by Jobclaw from real GitHub repositories.',
      images: [`/portfolio/${id}/opengraph-image`],
    },
  };
}

async function getPublicDoc(id: string): Promise<Doc | null> {
  const res = await fetch(`${API_BASE}/v1/documents/${id}/view`, { cache: 'no-store' });
  if (!res.ok) return null;
  return res.json();
}

export default async function PublicPortfolioPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const doc = await getPublicDoc(id);
  if (!doc) notFound();

  return (
    <main className="min-h-screen bg-background text-foreground">
      <div className="mx-auto max-w-3xl px-6 py-12">
        <p className="mb-1 font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">
          Software Portfolio · Jobclaw
        </p>
        <h1 className="mb-10 font-heading text-3xl font-bold">{doc.name}</h1>

        {doc.sections.map((s) => (
          <div key={s.assessmentId} className="mb-10 border-t border-border pt-8">
            <p className="mb-1 font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
              {s.repoOwner}/{s.repoName}
            </p>
            <h2 className="mb-2 text-xl font-bold">{s.headline}</h2>
            <div className="mb-4 flex flex-wrap gap-4 font-mono text-xs text-muted-foreground">
              <span>{s.role}</span>
              <span>{s.duration}</span>
              <span>Score: {s.overallScore}/100</span>
            </div>
            <p className="mb-4 text-sm leading-relaxed">{s.summary}</p>
            <p className="mb-4 font-mono text-xs text-muted-foreground">
              <strong className="text-foreground">Stack:</strong> {s.techStack.join(', ')}
            </p>
            <ul className="mb-4 space-y-2 pl-4 text-sm">
              {s.highlights.map((h) => (
                <li key={h.title} className="list-disc">
                  <strong>{h.title}:</strong> {h.description}
                </li>
              ))}
            </ul>
            <p className="border-l-2 border-primary pl-3 text-sm italic text-muted-foreground">
              {s.impact}
            </p>
          </div>
        ))}

        <p className="mt-16 text-center font-mono text-[10px] text-muted-foreground/50">
          Generated by{' '}
          <a href="https://jobclaw.fyi" className="hover:underline">
            Jobclaw
          </a>
        </p>
      </div>
    </main>
  );
}
