'use client';

import { Icon } from '@iconify/react';
import { useRouter } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';

import { ShareModal } from '../../components/share-modal';
import { useApi } from '../../lib/api-context';

type DocumentItem = {
  id: string;
  name: string;
  status: 'ACTIVE' | 'DRAFT' | 'ARCHIVED';
  sizeLabel: string | null;
  tags: string[];
  createdAt: string;
  projectId: string;
  projectName: string;
};

const STATUS_STYLE: Record<DocumentItem['status'], string> = {
  ACTIVE: 'text-emerald-700 bg-emerald-50 border-emerald-200',
  DRAFT: 'text-amber-700 bg-amber-50 border-amber-200',
  ARCHIVED: 'text-muted-foreground bg-muted border-border',
};

const STATUS_TABS = ['ALL', 'ACTIVE', 'DRAFT', 'ARCHIVED'] as const;
type Tab = (typeof STATUS_TABS)[number];

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

type Section = {
  assessmentId: string;
  repoOwner: string;
  repoName: string;
  overallScore: number;
  headline: string;
  summary: string;
  role: string;
  duration: string;
  techStack: string[];
  highlights: { title: string; description: string }[];
  impact: string;
};

function esc(s: unknown): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function generatePortfolioHtml(name: string, sections: Section[]): string {
  const sectionsHtml = sections
    .map(
      (d) => `
    <div class="section">
      <div class="repo">${esc(d.repoOwner)}/${esc(d.repoName)}</div>
      <div class="headline">${esc(d.headline)}</div>
      <div class="meta">
        <span>${esc(d.role)}</span>
        <span>${esc(d.duration)}</span>
        <span>Score: ${Number(d.overallScore)}/100</span>
      </div>
      <p class="summary">${esc(d.summary)}</p>
      <div class="tech"><strong>Tech Stack:</strong> ${d.techStack.map(esc).join(', ')}</div>
      <div class="highlights-label">Highlights</div>
      <ul>${d.highlights.map((h) => `<li><strong>${esc(h.title)}:</strong> ${esc(h.description)}</li>`).join('')}</ul>
      <div class="impact">${esc(d.impact)}</div>
    </div>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${esc(name)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Georgia, 'Times New Roman', serif; max-width: 780px; margin: 0 auto; padding: 48px 40px; color: #1a1a1a; font-size: 14px; line-height: 1.6; }
    h1 { font-size: 2rem; font-weight: 700; margin-bottom: 4px; letter-spacing: -0.02em; }
    .subtitle { color: #666; margin-bottom: 40px; font-size: 0.9rem; }
    .section { margin-bottom: 36px; padding-top: 28px; border-top: 1.5px solid #e2e2e2; page-break-inside: avoid; }
    .repo { font-family: 'Courier New', monospace; font-size: 0.75rem; color: #888; text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 4px; }
    .headline { font-size: 1.15rem; font-weight: 700; margin-bottom: 8px; }
    .meta { display: flex; gap: 16px; font-size: 0.8rem; color: #555; margin-bottom: 12px; }
    .meta span::before { content: '·'; margin-right: 4px; color: #ccc; }
    .meta span:first-child::before { content: ''; margin-right: 0; }
    .summary { margin-bottom: 12px; color: #333; }
    .tech { font-size: 0.82rem; color: #555; margin-bottom: 14px; }
    .highlights-label { font-size: 0.72rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.12em; color: #999; margin-bottom: 6px; }
    ul { padding-left: 18px; margin-bottom: 14px; }
    li { margin-bottom: 5px; color: #333; }
    .impact { font-style: italic; color: #444; padding-left: 14px; border-left: 3px solid #c96442; }
    @media print { body { padding: 20px; } .section { page-break-inside: avoid; } }
  </style>
</head>
<body>
  <h1>${esc(name)}</h1>
  <div class="subtitle">Generated by Jobclaw</div>
  ${sectionsHtml}
</body>
</html>`;
}

export default function DocumentsPage() {
  const { get, authToken } = useApi();
  const router = useRouter();
  const [documents, setDocuments] = useState<DocumentItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState('');
  const [tab, setTab] = useState<Tab>('ALL');
  const [downloadingId, setDownloadingId] = useState<string | null>(null);
  const [sharingDoc, setSharingDoc] = useState<DocumentItem | null>(null);

  useEffect(() => {
    if (!authToken) {
      setLoading(false);
      return;
    }
    setLoading(true);
    get<{ items: DocumentItem[] }>('/v1/documents')
      .then((data) => setDocuments(data.items))
      .catch(() => setDocuments([]))
      .finally(() => setLoading(false));
  }, [get, authToken]);

  const filtered = useMemo(() => {
    return documents.filter((d) => {
      const matchesTab = tab === 'ALL' || d.status === tab;
      const matchesQuery =
        d.name.toLowerCase().includes(query.toLowerCase()) ||
        d.projectName.toLowerCase().includes(query.toLowerCase());
      return matchesTab && matchesQuery;
    });
  }, [documents, query, tab]);

  async function handleDownload(doc: DocumentItem) {
    setDownloadingId(doc.id);
    try {
      const data = await get<{ name: string; sections: Section[] }>(`/v1/documents/${doc.id}`);
      const html = generatePortfolioHtml(data.name, data.sections);
      const blob = new Blob([html], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${data.name.replace(/\s+/g, '-').toLowerCase()}.html`;
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      // silently ignore
    } finally {
      setDownloadingId(null);
    }
  }

  function handleShare(doc: DocumentItem) {
    setSharingDoc(doc);
  }

  function handleEdit(doc: DocumentItem) {
    router.push(`/builder?load=${doc.id}`);
  }

  return (
    <>
    <main className="min-h-screen bg-background text-foreground">
      <header className="sticky top-0 z-10 border-b border-border bg-background/90 backdrop-blur">
        <div className="mx-auto max-w-6xl px-6 py-6">
          <div className="mb-1 flex items-center gap-2">
            <Icon icon="solar:folder-bold" className="text-lg text-primary" />
            <span className="font-mono text-[9px] font-bold uppercase tracking-[0.2em] text-muted-foreground">
              Your Portfolios
            </span>
          </div>
          <h1 className="font-heading text-3xl font-bold">Portfolios</h1>
          <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center">
            <div className="relative flex-1 max-w-md">
              <Icon
                icon="solar:magnifer-linear"
                className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"
              />
              <input
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Search by name or project…"
                className="w-full rounded-full border border-border bg-card py-2 pl-9 pr-4 text-sm focus:outline-none focus:ring-2 focus:ring-primary/30"
              />
            </div>
            <div className="flex gap-1">
              {STATUS_TABS.map((t) => (
                <button
                  key={t}
                  type="button"
                  onClick={() => setTab(t)}
                  className={`rounded-full px-3 py-1.5 font-mono text-[10px] font-bold uppercase tracking-wide transition-colors ${
                    tab === t
                      ? 'bg-primary text-primary-foreground'
                      : 'text-muted-foreground hover:text-foreground'
                  }`}
                >
                  {t}
                </button>
              ))}
            </div>
          </div>
        </div>
      </header>

      <section className="mx-auto max-w-6xl p-6">
        {loading && (
          <p className="font-mono text-xs text-muted-foreground">Loading documents…</p>
        )}
        {!loading && !authToken && (
          <p className="font-mono text-xs text-muted-foreground">Sign in to view your documents.</p>
        )}
        {!loading && authToken && filtered.length === 0 && (
          <div className="py-16 text-center">
            <Icon icon="solar:folder-open-linear" className="mx-auto mb-3 text-4xl text-muted-foreground/40" />
            <p className="font-mono text-sm text-muted-foreground">
              {query || tab !== 'ALL'
                ? 'No portfolios match your filter.'
                : 'No portfolios yet.'}
            </p>
            {!query && tab === 'ALL' && (
              <a
                href="/builder"
                className="mt-4 inline-flex items-center gap-1.5 font-mono text-xs font-bold text-primary hover:underline"
              >
                Go to Build to create your first portfolio
                <Icon icon="solar:arrow-right-linear" className="text-sm" />
              </a>
            )}
          </div>
        )}

        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {filtered.map((doc) => (
            <article
              key={doc.id}
              className="flex flex-col gap-4 rounded-xl border border-border bg-card p-5 transition-shadow hover:shadow-sm"
            >
              <div>
                <div className="mb-2 flex items-start justify-between gap-2">
                  <div className="min-w-0 flex-1">
                    <button
                      type="button"
                      onClick={() => handleEdit(doc)}
                      className="truncate font-mono text-xs font-bold hover:text-primary hover:underline text-left w-full"
                    >
                      {doc.name}
                    </button>
                    <p className="mt-0.5 font-mono text-[9px] text-muted-foreground">
                      {doc.projectName}
                    </p>
                  </div>
                  <span
                    className={`shrink-0 rounded-full border px-2 py-0.5 font-mono text-[9px] font-bold uppercase ${STATUS_STYLE[doc.status]}`}
                  >
                    {doc.status}
                  </span>
                </div>
                <p className="font-mono text-[9px] text-muted-foreground">
                  {formatDate(doc.createdAt)}
                  {doc.sizeLabel ? ` · ${doc.sizeLabel}` : ''}
                </p>
              </div>

              {doc.tags.length > 0 && (
                <div className="flex flex-wrap gap-1.5">
                  {doc.tags.map((tag) => (
                    <span
                      key={tag}
                      className="rounded border border-border bg-muted px-2 py-0.5 font-mono text-[9px] text-muted-foreground"
                    >
                      {tag}
                    </span>
                  ))}
                </div>
              )}

              <div className="mt-auto flex gap-2">
                <button
                  type="button"
                  onClick={() => handleDownload(doc)}
                  disabled={downloadingId === doc.id}
                  className="flex flex-1 items-center justify-center gap-1.5 rounded-lg border border-border py-2 font-mono text-[10px] font-bold uppercase tracking-wide transition-colors hover:bg-muted disabled:opacity-50"
                >
                  <Icon
                    icon={downloadingId === doc.id ? 'solar:spinner-linear' : 'solar:download-linear'}
                    className={`text-sm ${downloadingId === doc.id ? 'animate-spin' : ''}`}
                  />
                  {downloadingId === doc.id ? 'Preparing…' : 'Download'}
                </button>
                <button
                  type="button"
                  onClick={() => handleShare(doc)}
                  className="flex flex-1 items-center justify-center gap-1.5 rounded-lg border border-border py-2 font-mono text-[10px] font-bold uppercase tracking-wide transition-colors hover:bg-muted"
                >
                  <Icon icon="solar:share-linear" className="text-sm" />
                  Share
                </button>
              </div>

              <button
                type="button"
                onClick={() => handleEdit(doc)}
                className="flex w-full items-center justify-center gap-1.5 rounded-lg bg-primary/10 py-2 font-mono text-[10px] font-bold uppercase tracking-wide text-primary transition-colors hover:bg-primary/20"
              >
                <Icon icon="solar:pen-linear" className="text-sm" />
                Edit in Builder
              </button>
            </article>
          ))}
        </div>
      </section>
    </main>

    {sharingDoc && (
      <ShareModal
        title={sharingDoc.name}
        shareUrl={`${typeof window !== 'undefined' ? window.location.origin : 'https://jobclaw.fyi'}/portfolio/${sharingDoc.id}`}
        ogImageUrl={`${typeof window !== 'undefined' ? window.location.origin : 'https://jobclaw.fyi'}/portfolio/${sharingDoc.id}/opengraph-image`}
        shareText="Check out my software portfolio — built from real GitHub repos with AI-powered analysis on Jobclaw."
        onClose={() => setSharingDoc(null)}
      />
    )}
  </>
  );
}
